grammar = node+

node = upperIdent '=' rule

rule = altRule

altRule = seqRule ('|' seqRule)*

seqRule = atom+

postfix = atom ('?' | '*')?

atom = upperIdent
     | labelRule
     | '\'' char* '\''
     | '(' rule ')'

labelRule = label:('ident' ':') atom
